# 主页项目审计报告（2026-09-18）

审计对象：`D:\OneDrive\RUC\homepage`（git 分支 main，HEAD c90ca8b）
审计方式：10 个切片的只读审计 + 对 critical/high 发现的对抗性复核
本报告的严重度 = 原始定级，并在每条后给出**对抗性复核后的修正定级**

---

## 0. 执行摘要

先说最该动手的 5 件事，每件一句话说清后果：

1. **处理 CV PDF 里的手机号/出生日期，并顺手收紧线上发布面。** `cv/RUC_CV.pdf` 由 `index.html:246` 直接提供下载，PDF 内含手机号、出生日期、籍贯、政治面貌；站点是**从仓库根发布**的（实测线上 `scripts/`、`data/`、`cv/` 都可直接下载），所以这些内容对搜索引擎可见。后果：可被直接用于定向诈骗与社工。**注意**：复核把这条的严重度从 critical 下调为 medium——数据主体就是作者本人，`index.html:259-291` 本就公开三个邮箱、两个单位和门牌地址，手机号只是同类信息的边际增量；"扫描完全隐形"也不成立，`pdftotext` 一次就读出来。该修，但不必当事故处理。
2. **修 visual-regression 常红。** Site Checks 全历史 88 次运行 86 次失败，最后一次绿是 run #73（2026-08-28），当前 HEAD 仍是红；#83–#88 唯二失败的 job 一直是 `visual-regression`，根因是整页截图尺寸（基线 1440x7776 vs 实测 1440x8181）。后果：整条 CI 失去红/绿信号，链接失效、a11y 回归、Lighthouse 掉分都被这一个红位盖住。
3. **修语言切换把日期改回 2026-08-10。** 动态日期只在 `scripts/main.js:1614` 的 `loadSiteMeta` 里取过一次，而语言切换走的 `applyI18nText` 会无条件重写所有 `[data-i18n]` 节点。后果：任何访客点一次 EN 再切回中文，简历区与页脚就显示 5 周前的错误日期，刷新才恢复。
4. **决定 4 份 CNKI 出版社排版 PDF 的去留。** `papers/2021/mgtwr-variable-selection/mgtwr.pdf`、`papers/2022/gtwr-housing/gtwr.pdf`、`papers/2022/bgtwr-housing/bgtwr.pdf`、`papers/2025/poisson-rr/poisson-rr.pdf` 的 PDF 元数据是 `Producer: CNKI...`，正文带出版社 DOI，等于在公开站点再分发出版社排版全文。后果：存在被 DMCA 下架、进而整站 Pages 受限的风险。**（这条未做对抗性验证，需你先确认自存档政策。）**
5. **给 `data/paper-pages.json` 定身份。** `README.md:23` 把它写成 "paper page configuration"，但它实际是 `scripts/build-site-data.js` 的生成物，同时被 `scripts/generate-paper-toc.js:7` 当输入读，而机器人每次 push 后用 `git add -A` 覆盖它。后果：按文档手改 TOC / `pdf_candidates` / `path` 会被静默回滚。**（该条对抗性验证结论是 `not_verified`，需人工确认后再动手。）**

总账：71 条 finding（1 critical / 11 high / 49 medium / 10 low），含跨切片重复。对抗性复核只覆盖了 12 条 critical/high 中的 10 条：**2 条被证伪**（不要按原报告处理）、**1 条未验证**、**7 条现象成立但严重度下调**；另有 2 条 high 未进入复核，标为待人工确认。真正需要立刻动手的是上面第 1–3 条。

---

## 1. 高危项（原始定级 critical / high）

> **⚠️ 已证伪清单（不要按原报告处理）**
> - **导航逻辑改写 URL hash、吃掉筛选参数、使深链失效**（原始 high）→ **已证伪**，降为 low。理由见 1.11。
> - **未发表稿件的在审期刊名写进公开文件**（原始 high / security_privacy）→ **已证伪**，降为 low，残留问题属文档一致性。理由见 1.12。
>
> **待人工确认清单**
> - `data/paper-pages.json` 身份混淆（原始 high）：复核结论 `not_verified`，见 1.10。
> - 4 份 CNKI PDF 再分发（原始 high）：未进入复核，见 1.8。
> - GitHub Pages 从仓库根发布（原始 high）：未进入复核，见 1.9。

### 1.1 CV PDF 公开含手机号与出生日期

**原始定级 critical → 复核 confirmed，修正定级 medium**

**【现象+证据】**
- `index.html:246` 是 `<a class="cv-card" href="./cv/RUC_CV.pdf" download>`；`pdftotext -layout cv/RUC_CV.pdf` 两页页脚都输出 `houjian1997@ruc.edu.cn  13199819504`，首页"个人信息"块输出出生日期 `1997年01月27日`、籍贯、政治面貌、性别、民族。
- `cv/hou-jian-cv-zh.pdf`（1,241,081 B）同样含手机号与全部身份字段，`git ls-files cv` 确认已被跟踪，而全仓库 grep `hou-jian-cv-zh` 零页面引用（`index.html` 只引用 `RUC_CV.pdf:246` 与 `hou-jian-cv-en.pdf:250`）。
- 线上可达：`GET https://stork343.github.io/homepage/robots.txt` → 200 且与仓库内容一致；`robots.txt:2` 的 `Allow: /` 不拦 PDF。手机号在原始字节与 inflate 后的 stream 里都 grep 不到（文本经字体子集编码）。

**【后果】** 真实姓名 + 出生日期 + 籍贯 + 政治面貌 + 手机号在一个可被搜索引擎索引的公开站点上可下载。复核同时指出原报告夸大之处：数据主体即发布者，`index.html:259-291` 本就公开三个邮箱、两个单位与门牌地址，这些是中文简历的标准字段；"任何关键词扫描都发现不了"是所有 PDF 的通用性质，任何 PDF 感知扫描器都会命中，CI 也从未承诺扫 PDF 正文。所以这是**隐私卫生问题，不是泄密事故**。手机号可被视为已公开。

**【建议动作】**
1. 用不含手机号 / 出生日期 / 籍贯 / 政治面貌的版本重新生成 `cv/RUC_CV.pdf`，替换 `index.html:246` 的链接目标。
2. `git rm cv/hou-jian-cv-zh.pdf`（全仓库零引用；删前确认没有外部页面直链它）。**注意**：仓库里的 `cv/hou-jian-cv-zh.tex` 不是这两份 PDF 的源（它无手机号、只渲染 1 页），真正的源在仓库外，要先把源纳入仓库才能可持续重建。
3. 手机号按已泄露处理，视需要更换。
4. **历史清理不做**：`git filter-repo` + force push 属不可逆破坏性操作，会与公开 release bundle、内网预览等纠缠，需要单独评估；只换掉当前 HEAD 上的文件就已经覆盖"公开可下载"这一主要风险。

**【验证结论】** `confirmed`（4 项证据全部独立复现，字节数、行号、内容一致）。严重度按复核下调为 **medium**：无第三方 PII、无凭据、修复成本低。若作者明确表示手机号本不打算公开，可自行上调到 high。

---

### 1.2 visual-regression 门禁结构性常红

**原始定级 high → 复核 confirmed，修正定级 medium**

**【现象+证据】**
- GitHub Actions：Site Checks 共 88 次运行，failure=86 / success=2；最后一次绿是 run #73（2026-08-28），当前 HEAD c90ca8b 的 run #88 仍是 failure。
- #83–#88 每次唯一失败的 job 都是 `visual-regression`，annotation 原文：`Expected an image 1440px by 7776px, received 1440px by 8181px`，指向 `tests/ui/visual.spec.js:19`。
- 基线 `tests/ui/visual.spec.js-snapshots/homepage-main-chromium-darwin.png` 的 PNG IHDR 实测就是 1440x7776；`tests/ui/visual.spec.js:19-21` 对 `page.locator("main")` 做整元素截图，元素高度等于首页内容高度。
- job 定义在 `.github/workflows/site-checks.yml:141-168`，跑在 macos-latest；`docs/MACMINI.md:155-166` 已给出"删掉 CI 视觉 job"的结论但未执行。

**【后果】** workflow 级结论永远是 failure，无法从红/绿一眼区分其它 job 的真实回归（审计窗口内 `link-check` 曾连续 64 次失败、`#79/#80` 的 `syntax-check` 也真实失败过）。复核修正三点：① "全历史唯一失败源是尺寸漂移"不成立——视觉 job 在 #1–#30 时还不存在，早期红是 `link-check` 造成的；② "其余 5 个 job 的真实回归被永久掩盖"偏重——run 页面逐 job 列状态，真实失败看得到，被掩盖的只有 workflow 级那一个红/绿位；③ **公开仓库的 macOS 托管 runner 不额外计费**，原报告"支付昂贵 macOS runner"是事实错误，真实代价只是排队与墙钟时间（#88 的 job 实测 41s）。

**【建议动作】**二选一，**推荐 ②**（它保留仓内门禁）：
- ① 删除 `.github/workflows/site-checks.yml:141-168` 整个 job，视觉只在 `scripts/ops/local-ci.sh --full` 跑。代价：`scripts/ops/local-ci.sh` 与 `docs/MACMINI.md` 目前是未跟踪状态，这么做之后仓库内不再有任何受强制的视觉门禁。
- ② 把 `tests/ui/visual.spec.js:19-21` 的"整页 `main`"改成与内容长度解耦的快照（固定视口截图，或只截 `.navbar`/`.topbar` 等定高组件），在 macos-latest 上重新生成 4 张基线并提交，同时把 `maxDiffPixelRatio` 收紧到 0.02。

**【验证结论】** `confirmed`。行号与数字逐条复核无误；原报告的计费影响与"全历史归因"被反证推翻，故修正为 medium。

---

### 1.3 切换语言把动态日期覆盖回硬编码 2026-08-10

**原始定级 high → 复核 confirmed，修正定级 medium**

**【现象+证据】**
- `index.html:255`（`.cv-updated`）与 `index.html:325`（`.footer-text`）是带 `data-i18n` 的日期节点。
- `scripts/main.js:1423-1444` 的 `loadSiteMeta` 用 `data/site-updated.generated.json`（实测 `{"updated":"2026-09-17"}`）覆盖它们，但 `scripts/main.js:384-391` 的 `applyI18nText` 对所有 `[data-i18n]` 节点无条件 `textContent = t(key)`，而 `scripts/main.js:414-419` 的 `setLanguage` 走的正是它。
- `loadSiteMeta` 全仓库只有 `scripts/main.js:1614` 一次调用（且在 `:1612` 的 `applyI18nText` 之后），语言切换路径没有任何重算入口。
- 静态值：`scripts/main.js:104` `cv_updated="最近更新：2026-08-10"`、`:116` `footer_text="…最后更新：2026年8月10日"`；英文侧 `:208`/`:220` 是 August 10, 2026。

**【后果】** 任何访客点一次语言按钮（中→英或英→中），简历区与页脚日期就从 2026-09-17 倒退到 2026-08-10（约 5.4 周）；页面刷新即恢复。`docs/QA_CHECKLIST.md:16` 明文要求日期跟随 `site-updated.generated.json`，所以这是回归而非设计。现有 CI 与 `scripts/acceptance-check.js` 都不检查这个 UI 回归。

**【建议动作】** 把 `loadSiteMeta` 解析出的日期存到模块级变量（如 `siteMetaUpdated`），在 `applyI18nText` 末尾对 `.cv-updated` / `.footer-text` 两个节点按 `formatI18n("cv_updated_template")` / `("footer_text_template")` 重放；或让 `setLanguage` 在 `applyI18nText` 之后 `await loadSiteMeta()`。不要让 `data-i18n` 的静态回退值承载动态日期。

**【验证结论】** `confirmed`。逐行核对无误，无第二处调用、无补偿路径、`t()` 是纯静态查表。确认为 medium 而非 high：只影响两处展示性文本，不参与任何逻辑、不影响 CV 下载或出版物渲染，刷新自愈，修复约一行。

---

### 1.4 `scripts/enrich-metadata.js` 默认即写入、`--check` 空转

**原始定级 high → 复核 confirmed，修正定级 medium**

**【现象+证据】**
- `scripts/enrich-metadata.js:302` `const writeCache = args.has("--write-cache") || !args.has("--check");` —— 不传任何参数等于写入。
- `:328-331` 无条件写 `data/metadata-cache.generated.json`，该文件被 git 跟踪且未被 `.gitignore`。
- `--check` 分支只跳过写入并打印 META 行：不做任何比较、不设非零退出码；`:314-326` 每次从零重建 payload，不与旧 cache 合并。
- 漂移已存在：cache 14 条 vs master 16 条，缺 `salcdi-scarce-outcomes`、`qtr-oc`（对应 `data/publications.json` 里这两条 `"metadata": null`）。
- `.github/workflows/site-checks.yml` 里没有任何步骤跑它；`package.json` 的 `check:syntax` 也没列入它。

**【后果】** 裸跑 `node scripts/enrich-metadata.js` 会静默改写被跟踪文件——与同 toolchain 其它脚本"无参数=check/dry-run"（`build-site-data.js:479`、`generate-paper-toc.js:73`、`sync-paper-seo.js:76`）的约定完全相反；`--check` 永远退出 0，给人"校验通过"的假信号。复核修正两点：① "断网会把 DOI 静默写空"**不成立**——`mergeDetectedMetadata`（`:204-230`）先做纯离线的本地 DOI 提取，实测 cache-only DOI 数 = 0，网络失败不会清空已有 DOI；真正会丢的是 2 条 cache-only arXiv ID（svcqr 2511.18106、snqesa 2510.24352）。② 原报告引用 master `data_version=2026-09-17`、`publications=16` 有误（实际 `data_version=2026-08-28`，`publications.json` 是 15 条顶层数组）。

**【建议动作】**
1. `scripts/enrich-metadata.js:302` 改为 `const writeCache = args.has("--write-cache");`。
2. 在 `--check` 分支实现真实的只读比较：读 `CACHE_FILE`，逐条核对 `id` 覆盖 master 全部 publication、JSON 可解析；缺失或损坏就 `process.exitCode = 1`。
3. 写入前先合并旧 cache，网络失败条目沿用旧值。
4. 把 `node --check scripts/enrich-metadata.js` 加进 `package.json` 的 `check:syntax`。
**注意**：不要把 `--check` 直接当作"离线比较"加进 CI——该路径仍会对缺 DOI 的条目发 Crossref/arXiv 请求；要离线校验需另写一条不联网的路径。

**【验证结论】** `confirmed`。机制、漂移、`git add -A` 的影响都属实；DOI 清空这一危害被代码自身排除，故降为 medium。

---

### 1.5 回归用例的导出断言只认文件名前缀

**原始定级 high → 复核 confirmed，修正定级 medium**

**【现象+证据】**
- `tests/ui/regression.spec.js:133-141`：只断言下载文件名含 `filtered` 与 `.bib`，不读内容、不做筛选前后计数对比。
- `scripts/main.js:1358-1366`：`records = getExportRecords(Boolean(filteredOnlyInput.checked))`，而 `prefix` 只由复选框决定（`t("export_file_filtered")`），文件名与记录来源相互独立；`:1260-1261` 的 `getExportRecords` 在 filteredOnly 为真时取 `getFilteredPublications()`。若该函数回归成返回全量，文件名不变、用例照样绿。
- RIS/EndNote 实现见 `scripts/main.js:1373-1378`、`index.html:230-231`；站内检索输入框见 `index.html:221`。这两组在 `tests/` 下 0 命中。

**【后果】** 导出中心"勾选仅导出筛选结果时，导出集合必须等于页面可见集合"这条契约没有内容级断言；RIS/EndNote 两个独立 builder、独立的 MIME 与 `.ris`/`.enw` 扩展名完全不测。复核修正：原报告"零覆盖、仅 scripts/main.js 与 index.html 有"**不准确**——`scripts/acceptance-check.js:116-125` 对筛选下拉与导出按钮的 ID 逐项做静态断言并在 CI 运行（`.github/workflows/site-checks.yml:71-72`），`scripts/acceptance-check.js:300-303` 还登记了人工验证项；且渲染（`scripts/main.js:1212`）与筛选导出（`scripts/main.js:1261`）共用同一个 `getFilteredPublications()`，"导出集合 = 页面可见集合"有结构保证。

**【建议动作】** 用 `await download.createReadStream()` 读 `.bib` 文本（或 `await download.path()` 后 `fs.readFileSync`），断言条目数等于页面卡片数、且被筛掉的记录不存在；补"未勾选复选框 = 全量"的对照断言；对 RIS/EndNote 复制同一组断言（`#export-ris-btn`→`.ris`、`#export-endnote-btn`→`.enw`）；补一条 `#pub-search-input` 输入不可能字符串 → 卡片数为 0 的边界用例，再点 `#pub-clear-btn` 断言恢复全量。

**【验证结论】** `confirmed`。当前代码没有现存缺陷，属测试覆盖缺口 + 断言设计问题，定 medium。

---

### 1.6 `scripts/ops/backup-homepage.sh` 打印裸 `rsync --delete`

**原始定级 high → 复核 confirmed，修正定级 medium**

**【现象+证据】**
- `scripts/ops/backup-homepage.sh:71-72` 结尾打印可复制命令：`Restore command:` / `rsync -a --delete "$BACKUP_DIR/homepage/" "$SRC/"`。
- `README.md:76-84` 文档化的入口是 `./scripts/ops/restore-homepage.sh --backup /path/to/backup-dir`；`docs/RELEASE_ROLLBACK.md:59-62` 承诺"默认会先做安全快照"，该快照在 `scripts/ops/restore-homepage.sh:72-78`，`.git` 校验在 `:65-68`。
- 全仓库 grep 显示这个裸命令只出现在该脚本的 heredoc 输出里，没有任何 CI、hook 或文档说明两条路径不等价。

**【后果】** 照抄打印出来的命令会在无快照、无 `.git` 校验的情况下用 `--delete` 覆盖活工作树。复核修正：① 这是"打印文本"，必须人工复制执行，没有无人值守路径；② 它紧跟刚完成的备份打印，立即执行几乎是空操作，真要出事是事后拿旧备份去跑；③ `restore-homepage.sh:80-85` 的默认本身就是 `rsync -a --delete`，差别只是"多一个可恢复快照"，不是"安全 vs 不安全"；④ `.git` 校验对该脚本自产备份恒通过（备份包含 `.git`）。真正会丢的只是备份之后新建的未跟踪文件。

**【建议动作】** 把 `scripts/ops/backup-homepage.sh:71-72` 的输出改为 `./scripts/ops/restore-homepage.sh --backup <BACKUP_DIR>`（可附一行"加 `--no-delete` 保留多余文件"）；或在 `README.md:80-84` 的 Examples 后补一句"本仓库的还原入口是 `restore-homepage.sh`；裸 `rsync -a --delete` 无安全快照，仅限空目录/灾备"。

**【验证结论】** `confirmed`。行号引用逐条精确；影响是人工触发、条件性的，故 medium。

---

### 1.7 7.89 MiB 仅被根目录 LaTeX deck 引用的图片留在 papers/ 发布树里

**原始定级 high → 复核 confirmed，修正定级 low**

**【现象+证据】**
- `beamer_presentation.tex` 的 10 处 `\includegraphics`（:67、:84、:101、:118、:135、:152、:169、:186、:203、:220）是这 10 个文件的唯一引用者，合计 8,273,739 B（7.890 MiB）。
- `papers/` 下被跟踪图片共 51 个 11,644,091 B，其中只有 1,901,079 B（16%）被任何页面引用。
- `scripts/run-lighthouse-check.js:27-28` 的 1.8 MB 预算只测 `/index.html`（`.github/workflows/site-checks.yml:187-188` 无 `LH_URLS` 覆盖），卡片封面本来就是懒加载（`scripts/main.js:1143`），所以这不是性能问题。

**【后果】** 这 10 个文件不是普通孤儿，而是 deck 的构建输入——删掉会坏 LaTeX 构建，因此会永久留在每次 clone 与线上树里。复核修正（重要）：① 原报告建议的 `git mv` 到 `talks/figures/` **零收益**（它自己承认 `talks/` 仍会被发布），只增加改坏 `\includegraphics` 路径的风险；② `magick mogrify -format jpg` 有损转换会降低折线/散点图可读性，而仓库里 `papers/` 的 `.webp` 衍生件无法从仓库复现，PNG 是不可再生母版，覆盖不可逆；③ 真正"谁都不引用"的是**另一批 11 个文件**（约 1.23 MiB），不是这 10 个；④ 原报告漏掉一处真冗余：`papers/2025/hcqr/data-line.png`/`.webp` 与已被站点引用的 `papers/2025/hcqr/hcqr-cover-2026.png`/`.webp` 的 SHA256 完全相同（同 87,387 / 21,856 B）。

**【建议动作】** 只做低风险的那一步：把 `beamer_presentation.tex:118` 指向 `papers/2025/hcqr/hcqr-cover-2026.png`，然后 `git rm papers/2025/hcqr/data-line.png papers/2025/hcqr/data-line.webp`。10 张 deck 图先不动；要减体积需连同 deck 的组织方式一起决策（例如独立 talk 仓库 / Git LFS），不要就地覆盖母版 PNG。

**【验证结论】** `confirmed`（字节数、行号、引用面全部复现），但严重度修正为 **low**：无任何页面请求这些文件，运行时/安全/SEO 零影响，属一次性约 7.9 MB 克隆体积的资产治理项。

---

### 1.8 4 份 CNKI 出版社排版 PDF 被公开再分发

**原始定级 high → 未进入对抗性验证（待人工确认）**

**【现象+证据】**
- `pdfinfo` 显示 `papers/2021/mgtwr-variable-selection/mgtwr.pdf`、`papers/2022/gtwr-housing/gtwr.pdf`、`papers/2022/bgtwr-housing/bgtwr.pdf`、`papers/2025/poisson-rr/poisson-rr.pdf` 的 Producer/Author 是 CNKI 系（`CNKI®ReaderEx(...)`、`Author: CNKI`、`TTKN`）。
- 正文含出版社 DOI，证明是已发表定稿版而非作者稿：`pdftotext -layout -f 1 -l 1 papers/2022/bgtwr-housing/bgtwr.pdf -` 输出 `DOI:10.16722/j.issn.1674-537x.2022.10.001`。
- 对照可区分作者稿：`papers/2025/svcqr/svcqr.pdf` = `Creator: arXiv GenPDF`，`papers/2025/hcqr/hcqr.pdf` = `Producer: pdfTeX-1.40.26`。
- 对外提供路径：各 paper 页的 `window.__PAPER_PDF_URL__`，如 `papers/2022/bgtwr-housing/bgtwr.html:677`；`scripts/validate-site.js:307-311` 会因"未引用或未发布 PDF"直接 fail，说明引用是有意保留的。

**【后果】** 在公开仓库与公开站点再分发出版社排版全文，形成著作权/自存档合规风险；最坏情况是出版社/CNKI 提 DMCA，处置结果是整个 Pages 站点下线或仓库受限，影响远超这 4 个文件。

**【建议动作（需先确认自存档政策）】** 删除这 4 份 PDF（用 `git rm`，可由 git 历史回滚），把 `data/site-master.json` 中对应条目的 `links.pdf` 改指期刊 DOI 页（若有自存档许可则换为作者接受稿），然后重建派生数据：
```
node scripts/build-site-data.js --write
node scripts/sync-paper-seo.js --write
node scripts/generate-paper-toc.js --write
```
保留 `papers/2025/svcqr/svcqr.pdf` 与 `papers/2025/hcqr/hcqr.pdf` 两份作者稿。

**【验证结论】** **待人工确认**。证据是 `pdfinfo`/`pdftotext` 的直接输出，但"是否允许自存档"取决于各期刊政策，超出仓库审计的可判定范围。

---

### 1.9 GitHub Pages 从仓库根发布：内部脚本/文档/数据在公网可下载

**原始定级 high → 未进入对抗性验证（待人工确认）**

**【现象+证据】**
- 实测 `GET https://stork343.github.io/homepage/scripts/enrich-metadata.js` 返回 200；同域 `robots.txt` 返回 200 且与仓库一致。
- 发布机制：仓库根有已跟踪的 `.nojekyll`；`.github/workflows/` 里 grep `pages|deploy-pages|upload-pages` 只命中注释。站点自身依赖这种暴露：`index.html:340` 引 `scripts/main.js`，`scripts/main.js:1405` fetch `data/publications.json`。
- 同批暴露（`git ls-files` 根文件）：`package.json`、`package-lock.json`、`playwright.config.js`、`CHANGELOG.md`、`beamer_presentation.tex`。`docs/MACMINI.md:193` 已知情。
- 附带：`data/site-master.json` 随之线上可读，因此 `hidden:true` 的条目（如 `qapsm-icu-bp`）只是"不渲染"，不是"不公开"。

**【后果】** 待提交的 `scripts/ops/*.sh`、`docs/MACMINI.md` 一旦提交即公开，内含 Mac mini 常开 CI 运行器、局域网预览地址与端口、launchd 标签、日志路径与 `~/Sites/homepage` 目录结构。与 1.1 的手机号叠加后，这些运维文档把主机类型、内网端口、服务名与内网路径一并交给攻击者，构成可执行的定向侦察面；`scripts/enrich-metadata.js:76`/`:88` 还把个人 QQ 邮箱 `beidaihe77@qq.com` 固化为爬虫 User-Agent 字符串，随公开源码长期存在。

**【建议动作】** 让 Pages 不再发布整个工作树：改用 Actions 部署并白名单产物目录（`actions/upload-pages-artifact` 的 `path` 只指向站点产物目录），workflow 加 `permissions: contents: read` + `pages: write` + `id-token: write`。若暂不改造，至少把运维资料移到不发布的目录——注意本仓库已关闭 Jekyll（`notes/_book` 因为 `.nojekyll` 反而被发布），改目录时要一并确认意图。顺手把 `scripts/enrich-metadata.js` 两处 `mailto:` 的个人 QQ 邮箱换成项目专用地址。

**【验证结论】** **待人工确认**。线上 200 是实测；发布机制由"根有 `.nojekyll` + 无部署 workflow"推断，建议在 GitHub 仓库 Settings → Pages 核对 Source 是否为 "Deploy from a branch / main / (root)"。

---

### 1.10 `data/paper-pages.json` 身份混淆（生成物被当配置）

**原始定级 high → 复核结论 `not_verified`（待人工确认）**

**【现象+证据】**
- 生成侧：`scripts/build-site-data.js:12` 把 `paperPages` 列入 `OUTPUT_FILES`；`:191-196` `buildPaperPages(master)` 由 master 派生；`:500` 写入。实测 `node scripts/build-site-data.js --check` 输出 `OK: data\paper-pages.json is up-to-date.`，证明磁盘文件与 master 的派生结果逐字节相同。
- 消费侧把它当配置：`scripts/generate-paper-toc.js:7` `const SOURCE_FILE = path.join(ROOT, 'data', 'paper-pages.json')`（把它当唯一数据源）；`scripts/validate-site.js:9,56-59,97-99` 校验其内容；`scripts/acceptance-check.js:8,87,107` 以它为准。
- 文档：`README.md:23` 只写 ``data/paper-pages.json`: paper page configuration.`（相邻 :22/:24 都明确标了 generated / cache）。
- 自动覆盖：`.github/workflows/auto-sync-generated.yml:36` 跑 `--write`，`:44` 跑 `git add -A`，`:47` 用 GITHUB_TOKEN 直接 push `HEAD:main`。

**【后果】** 维护者按 `README.md:23` 的措辞手工修改 TOC、`pdf_candidates`、`toc_heading`、`path` 后，下一次 push 到 main 会被机器人用 `build-site-data --write` 静默重写成 master 的派生值并提交，改动无提示丢失；反向陷阱同样存在——`:44` 是 `git add -A`，机器人会把工作区里任何未预期文件一并提交。

**【建议动作（确认身份后再做）】**二选一，不要维持现状：
- (A) 认定它是生成物：`README.md:23` 改为 "`data/paper-pages.json`: **generated** paper page index (derived from `data/site-master.json`)"，并让 `scripts/generate-paper-toc.js:7` 改读 `data/site-master.json`（复用 `scripts/build-site-data.js:109-129` 的 `extractPaperPages`）。
- (B) 认定它是配置：从 `scripts/build-site-data.js:10-20` 的 `OUTPUT_FILES` 删除该项，`:491-501` 的 outputs 数组同步删除，让它变成只读输入，并修正 `validate-site.js` / `acceptance-check.js` 的期望。
- 无论哪种，都把 `auto-sync-generated.yml:44` 的 `git add -A` 收窄为显式清单（如 `git add data/ sitemap.xml index.html papers`）。

**【验证结论】** **`not_verified`**（对抗性复核未给出理由）。旁证：`data/` 切片把同一根因记为 medium（"paper-toc 双生成器 + paper-pages 是生成物却被写成 configuration"），文档切片也记了一条 medium。**建议先跑 `node scripts/build-site-data.js --check` 与 `node scripts/generate-paper-toc.js --check`，再定身份。**

---

### 1.11 【已证伪】导航逻辑改写 URL hash、吃掉筛选参数

**原始定级 high → 复核 verdict `refuted`，修正定级 low**
**⚠️ 已证伪，不要按原报告处理。**

**【原报告现象】** `scripts/main.js:1495-1499` 在 section 进入视口时执行 `history.replaceState(null, "", "#" + id)`，据称会丢弃 `?q=`/`?year=`；`#publication-*` 深链因此失效。

**【验证结论：已证伪】** 理由：
1. 只含 hash 的 URL 传给 `history.replaceState` 是相对当前文档的**片段引用，会继承查询串**（RFC 3986 §5.3）。实测 `new URL("#about", "https://x/y?q=abc&year=2024#z")` → `?q=abc&year=2024#about`。真实 Chrome 复现：访问 `/index.html?q=quantile` 后 hash 依次变成 `#about`→`#research`→`#cv`，但 `location.search` 始终是 `?q=quantile`，刷新后筛选输入框仍有 "quantile" 且 8 张卡片被筛出。所以"筛选参数被吃掉、链接无法分享、刷新回默认"这条**不成立**。
2. `#publication-*` 冷访问落不到卡片是**真实症状但归因错误**：卡片由 `scripts/main.js:1405` 的异步 fetch 渲染，目标元素在 fragment 滚动窗口内不存在时浏览器不会补跳（对照组：无站点 JS 的页面里，目标在 DOMContentLoaded 存在就能正确跳转，延迟 50 ms 插入就不跳）；用 localStorage 缓存预热时同一深链能正常落到卡片。所以单独保留 `#publication-` 并不能修好它。
3. `#publication-*` 只出现在 JSON-LD 的 `url` 字段（`data/publications-jsonld.generated.json` 中 5 条），站内无链接、无 `:target` 规则，爬虫也会剥离 fragment，"被搜索引擎收录的深链失效"夸大了影响。
4. 原报告"全仓只有 740/1481/1498 三处 replaceState"有误——`papers/shared/paper-reader.js:1293` 也调用。
5. 原报告建议 3 依赖 `.anchor-target` 机制，但该类名从未挂到任何元素（见 2.2），目前无法生效。

**【残留的真实缺陷（low，可选修）】** 渲染完成后没有回到 fragment 的代码，首次访问卡片深链会停在页首。可在 `loadPublications` 渲染完成后补：
```js
if (location.hash.indexOf("#publication-") === 0) {
  const el = document.querySelector(location.hash);
  if (el) el.scrollIntoView({ block: "start" });
}
```
原报告建议的"保留查询串"是无害但非必要的改动。

---

### 1.12 【已证伪】未发表稿件的在审期刊名写进公开文件

**原始定级 high / security_privacy → 复核 verdict `refuted`，修正定级 low**
**⚠️ 已证伪，不要按安全事件处理。**

**【原报告现象】** `beamer_presentation.tex:76`/`:93`/`:110`/`:127` 写有"期刊（在审）/（1st revision）/（Under Review）"；两份 CV PDF 的"投稿情况"段列在审期刊与返修轮次。

**【验证结论：已证伪】** 理由：
1. 站点**本身就是有意公开在审状态**的：线上 `data/publications.json` 与 `data/site-master.json`（:29-32、:84-86、:203-206、:325-327、:449-451）含"统计研究 / 状态：外审""JASA / 状态：外审"等（含 bibtex `note={Under external review}`）。原报告自己的整改建议也以该 `status` 字段为展示事实源，等于承认这是设计决策，不是失误泄漏。
2. 所列期刊为单盲刊，作者自列 under review 不涉双盲政策；无第三方 PII、无凭据、无攻击面，`security_privacy` 定性不成立。
3. 不构成增量披露，且内容陈旧：SNQESA 已出版于 Statistical Papers 67(5) 106、hcqr 已出版于 JSPI 245 106390、plgwqr 已网络首发、svcqr 已出版于 Spatial Statistics 74 100983，而 beamer/CV 仍标 in review / 1st revision。
4. 归因不准：GitHub 仓库本身公开，`.tex` 不经 Pages 也对外可读，删 Pages 副本不能真正撤回暴露。
5. 引用精度有瑕：原报告合并出的"应用数学学报[一修复审／外审]"在两份 PDF 中都不存在。

**【残留的真实问题（low，属文档一致性）】** 同一稿件状态在 `beamer_presentation.tex`、两份 CV、`data/site-master.json` 三处手工维护且互相矛盾。建议删掉或更新过时的"投稿情况 / 期刊（状态）"表述，站点展示统一以 `data/site-master.json` 的 status 为准，投稿台账改在仓库外私有维护。

---

## 2. 中低危项

按类别分组；每条给【位置】【问题】【建议】。标 **★** 的是同类中优先处理的代表项。

### 2.1 无效与遗留文件

- **medium** ★ `data/search-index.generated.json`（17.9 KB）——全仓库零消费者。唯一"验证"是 `scripts/validate-site.js:105-108` 的条目计数，而它与生成器同源、恒真。前端只 fetch 三个数据文件（`scripts/main.js:954`、`:1405`、`:1425`），站内检索是在 `scripts/main.js:684-710` 用 `publications.json` 现算的。**建议**：删除该文件，并清理 `scripts/build-site-data.js:14/:225-266/:486/:495`、`scripts/validate-site.js:11/:81/:86/:105-108`、`README.md:25`、`.github/workflows/site-checks.yml:47-48` 的引用。若确实想要预构建索引，必须在 `scripts/main.js` 里真的消费它。
- **medium** ★ `papers/` 下 12 个被跟踪图片（合计 1,469,273 B）零引用：`papers/2021/mgtwr-variable-selection/gtwr.webp`(60,078)、`papers/2022/bgtwr-housing/bgtwr.webp`(39,630)、`papers/2022/gtwr-housing/mgtwr.webp`(237,684)、`papers/2025/hcqr/data-line.webp`(21,856)、`papers/2025/jpdi-mixed-qr/dblqmm.webp`(56,462)、`papers/2025/mallows-llm-ranking/fig_estimation_convergence.webp`(97,934)、`papers/2025/plgwqr/plgwqr.webp`(130,872)、`papers/2025/poisson-rr/poisson-rr.webp`(6,508)、`papers/2025/snqesa/spx_plots.webp`(129,246)、`papers/2025/svcqr/log_price.png`(565,968)、`papers/2025/svcqr/log_price.webp`(100,304)、`papers/2026/jss-sssvcqr/jsslogo.jpg`(22,731)。其中 8 个是 deck-only PNG 的 webp 孪生（一次过宽的批量转码）。**建议**：确认后 `git rm`，并加一条 CI 断言防复发（遍历 `git ls-files papers` 的图片扩展名，与 `index.html` + `data/*.json` + `papers/**/*.html` + `beamer_presentation.tex` 的引用求差）。**注意**：`papers/2022/gtwr-housing/mgtwr.webp` 与 2021 版同名但 SHA256 不同，别用纯 basename grep 判断引用。
- **medium** `cv/hou-jian-cv-zh.pdf`（1.24 MB）——被跟踪但零页面引用，内容比 `cv/RUC_CV.pdf` 旧（源 `cv/hou-jian-cv-zh.tex:34` 仍写"更新日期：2026-02-24"），且随 Pages 公开。详见 1.1。
- **medium** `beamer_presentation.tex`（根目录，8852 B，229 行）——无人引用、无 CI 构建（`.github/workflows` 里 grep `pdflatex|xelatex|latexmk|beamer|\.tex` 0 命中），却通过 `:8` 的 `\graphicspath{{./}{./papers/}}` 与 11 处 `\includegraphics` 深耦合 `papers/` 资产；`0b3e158` 这种纯数据提交里已经被夹带改过一次。**建议**：优先迁到独立 talk 仓库；若保留，则移到 `notes/talks/`、把图片路径改成显式相对路径、在 README 登记构建命令，并把 LaTeX 产物加进 `.gitignore`。**不要为了"整理"就地删除它**——它是 1.7 里 10 张图的唯一消费者。
- **medium** `notes/_book/notes-book_files/figure-html/` 里 6 张无人引用的旧图（325,091 B：`gtwr-summary-1.png`、`hcqr-summary-1.png`、`mgtwr-summary-1.png`、`spa-plot-1.png`、`spa-summary-1.png`、`svcqr-summary-1.png`）与 `notes/_book/404.html`（26,287 B，嵌套目录里的 404 不会被 Pages 使用）。`notes/*.Rmd` 里已无对应 chunk（grep 0 命中），是产出代码被删后的残留；被 gitignore 的中间目录 `notes/notes-book_files/` 只有 7 个文件 119,451 B（正是被引用集合），证明本地产出链正常、只是 `_book/` 从不清理。**建议**：`git rm` 这 7 个文件，并在 `.github/workflows/build-bookdown-notes.yml:40-42` 的渲染步骤前加一步清空输出目录（该 step 已在 `working-directory: notes` 下；这些文件全部可由渲染再生）。
- **low** `icon/google.png`（2450 B）——被跟踪但零引用，Google Scholar 图标实际走 `index.html:116-122` 的内联 SVG（4 条 path）。**建议**：`git rm`，或反向统一成一种实现（二选一，别两种并存）。

### 2.2 死代码与重复

- **medium** ★ `.anchor-target` 从未挂到任何元素：`enhanced-main.css:272` 定义了 `scroll-margin-top:124px`，但 `index.html` 的 5 个 section（`:101`/`:173`/`:215`/`:242`/`:259`）都没有这个 class，全仓库只有这一处命中。而从 paper 页返回 `index.html#publications` 时走的是原生 fragment 跳转（如 `papers/shared/paper-reader.js:130`、`papers/2025/hcqr/hcqr.html:555`），不经过 `scripts/main.js:1476-1478` 的导航高度偏移，标题会被 84px 固定导航（`enhanced-main.css:237`）遮住。**建议**：把选择器改成 `main section[id]{scroll-margin-top:124px}`，或给 5 个 section 加 `class="anchor-target"`。
- **medium** ★ 同一份出版物 JSON-LD 有两套生成代码：`scripts/build-site-data.js:268-310`（从 `master.site.base_url` 生成，canonical 用 `#publication-<id>`，写 DOI identifier）vs `scripts/main.js:896-945`（客户端现算，canonical 用 `#publications`，无 identifier，且 `:908` 硬编码 origin）。调用关系见 `scripts/main.js:1411-1414`：生成文件拿不到才回退。**建议**：只保留 `applyGeneratedJsonLd`（`scripts/main.js:947-968`），删掉 `:896-945` 与回退分支；若需兜底，抽出共用的 `buildScholarlyItemList(publications)`。
- **medium** ★ 同一个产物 `data/paper-toc.generated.json` 有两个生成器：`scripts/build-site-data.js:198-223`（由 master 派生）与 `scripts/generate-paper-toc.js:32-57`（以 `data/paper-pages.json` 为输入）。两者日期缺省回退语义不同（`generate-paper-toc.js:33` 回退"今天" vs `build-site-data.js:201-202` 写空/1970），`data_version` 一旦为空，两个 `--check` 会互相判 OUTDATED。两条路径都跑：`.github/workflows/site-checks.yml:57/:60` 各 `--check`，`auto-sync-generated.yml:36/:38` 各 `--write`。**建议**：把 `generate-paper-toc.js` 降级为纯校验器，删 `package.json:12` 的 `toc:build`、`auto-sync-generated.yml:38`、`local-ci.sh:172` 的重复步骤，TOC 统一由 `build-site-data.js` 派生。
- **medium** 跨脚本重复实现：`const ROOT = path.resolve(__dirname, "..")` 在 8 个脚本各写一遍（`scripts/build-site-data.js:7`、`validate-site.js:6`、`acceptance-check.js:6`、`generate-paper-toc.js:6`、`sync-paper-seo.js:6`、`enrich-metadata.js:6`、`serve.js:6`、`run-lighthouse-check.js:9`）；`normalizeRelPath` 4 份且 `generate-paper-toc.js:36` 的写法与其余 3 份不一致（不剥 `./`）；`isHttpUrl` 4 处；`localizedText` 3 份行为不同（`build-site-data.js:73-78` trim / `enrich-metadata.js:18-23` trim+空白归一 / `main.js:596-601` 不 trim）；JSON-LD 2 份。**建议**：抽 `scripts/lib/paths.js`、`scripts/lib/data-io.js`、`scripts/lib/text.js`、`scripts/lib/jsonld.js`，8 个脚本改为 `require("../lib/...")`。
- **medium** DOI/arXiv 富化管线整体 write-only：`data/metadata-cache.generated.json`（4269 B）与 `data/publications.json` 里 14 个 `metadata` 块无人读取（`scripts/main.js`、`papers/`、`tests/` 对 `metadata` 零命中）；补全分支 `scripts/build-site-data.js:153-155` 实测零次生效（cache-only DOI 数 = 0），而 cache 与 master 已漂移（14 vs 16 条）。**建议**二选一，不要维持现状：(a) 真正接线——在 `buildPublicationsJsonLd` / `buildPaperSeo` 里用 `doi_url`/`arxiv_id` 补 `identifier`/`sameAs`，并给 `--check` 加离线校验；(b) 停用——删 cache 文件、删 `build-site-data.js:9/:64-71/:148-162` 的读取与注入、删 `publications.json` 的 `metadata` 字段、删 README 与 `package.json:22` 的相关条目。
- **medium** `papers/shared/reader.css`（332 行，5296 B）是死 CSS：全仓唯一引用是文档它的 `papers/README.md:28`；6 个 paper 页实际加载的是 `paper-theme.css`（`papers/2021/mgtwr-variable-selection/mgtwr.html:73` 等 6 处）与 `paper-reader.js`（`mgtwr.html:676` 等 6 处），而 `paper-reader.js` 里不含 `reader.css` 字符串，运行时也不会注入。**建议**：先 `git log --oneline -- papers/shared/reader.css` 确认无外部旧页面使用，再 `git rm` 并删 `papers/README.md:28` 那行。**别反向删 `paper-theme.css`**——那才是真正在用的。
- **medium** 6 个 paper 页是复制粘贴克隆（626/630/636/638/632/657 行；前 120 行两两有 85–96 行完全相同），共享资源的 cache-buster `?v=2026031006` 在 12 处手工维护，全仓库没有任何地方定义或校验它（`git grep -E '2026031006|ASSET_VERSION|CACHE_BUST' -- scripts data package.json index.html` 0 命中；`scripts/validate-site.js:317-334` 只校验 `paper-reader.js` 的能力片段）。**建议**：扩展现有的 `scripts/sync-paper-seo.js`（已经拥有 SEO marker）为 `sync-paper-shell.js`，用单一常量生成 head 与版本串，并把 `--check` 接进 `package.json` 的 `check:data`。
- **medium** `release-automation.yml` 全历史 0 次运行、仓库 0 个 Release、只有 1 个手工 tag（v2026.02.24），却是 `README.md:86-91`、`CHANGELOG.md:46/:51`、`docs/RELEASE_ROLLBACK.md:27-41` 指定的发布路径；`scripts/release.sh:79-87` 还会重跑一遍 CI 刚跑过的整套门禁（且 `:84-86` 里 a11y 又重复一次）。**建议**明确二选一：删除该 workflow 与 `scripts/release.sh`、把文档改写成 3 步手工 tag 流程；或先用一次性 dry-run tag dispatch 验证整链，并去掉发布前重复门禁。
- **low** 首页装饰层用 `display:none` 停用未删除：`enhanced-main.css` 的 74/83/95/97/114/147/154 共 7 组伪元素被永久关闭，配套 hover 规则（`:14`/`:21`/`:43`/`:16`）因此不可达；`.separator{display:none}`（`:125`）是全文件唯一的 separator 规则，而 `scripts/main.js:565-570` 的 `createSeparator()` 仍被每张卡片调用 6 次（`:1102-1114`），15 条成果产生约 90 个不可见节点。**建议**：删不可达规则与 `createSeparator` 调用，只靠 `column-gap:8px`（`enhanced-main.css:120`）。
- **low** `project-*` 系列选择器零引用仍在样式表内（`enhanced-main.css:28-42,52,55,63,251-252,266,298`），`scripts/main.js:322` 的 `REVEAL_SELECTOR` 还在观察 `.project-card`；另有一批自定义属性定义即死（`--space-2xs/xs/sm/md/lg/xl` 六个、`--tf-red`、`--tf-link-hover`）。**建议**：删除，并在清理后重跑 `node scripts/build-site-data.js --write` 刷新 `?v=` 哈希（当前 css=c7fd9ad5ab、js=86f1c56107），再跑 `node scripts/acceptance-check.js` 确认 0 FAIL。
- **low** `papers/2025/hcqr/data-line.png`/`.webp` 与 `papers/2025/hcqr/hcqr-cover-2026.png`/`.webp` SHA256 逐字节相同（87,387 / 21,856 B），只靠 `beamer_presentation.tex:118` 一行存活。**建议**：把 deck 指向 canonical 名后 `git rm papers/2025/hcqr/data-line.png papers/2025/hcqr/data-line.webp`。

### 2.3 文档与注释

- **medium** ★ `README.md:23` 把生成物 `data/paper-pages.json` 描述为 "paper page configuration"，与相邻 `:22`/`:24` 的 generated/cache 标注不一致，且全文没有出现 `paper_page` 或说明谁负责写它。详见 1.10。**建议**：按定论改成 "GENERATED (derived from `site-master.json` 的 `paper_page`, do not hand-edit)"，并补上未列出的 `data/metadata-cache.generated.json` 与 `data/site-updated.generated.json`。
- **medium** `papers/README.md:12-28` 的结构清单过期：漏掉整个 `papers/2026/`（7 个目录：jss-sssvcqr、qapsm-icu-bp、qtr-oc、qvsd-spatiotemporal-extremes、salcdi-scarce-outcomes、toms-sssvcqr、tplaqr）、漏掉实际在用的 `paper-reader.js` 与 `paper-theme.css`，`:37-41` 的重建配方还漏了 `generate-paper-toc.js --write`。**建议**：重写清单并对齐 `package.json` 的 `check:data`，再加一条 CI 断言让年份列表与 `git ls-files papers` 自动比对。
- **medium** 文档索引与实际文件不符：`CHANGELOG.md:12` 指向不存在的 `docs/workflows/`（全仓仅此一处，真正的模板是 `.github/workflows/auto-sync-generated.yml`）；`README.md:15-38` 的 Repository Layout 漏掉 `notes/`、`cv/`、`scripts/serve.js`、`scripts/ops/local-ci.sh`、`scripts/ops/macmini-bootstrap.sh`、`docs/MACMINI.md`。**建议**：修正指针并补相应行。
- **medium** 主题契约 `homepage-theme` / `data-theme` 跨 8 个文件（`index.html:29`、6 个 paper 页内联脚本第 10 行、`scripts/main.js:20`/`:464`、`papers/shared/paper-reader.js:509`/`:530`）无任何注释或文档声明；`index.html` 342 行内 `<!--` 零命中。测试只覆盖一条路径（`tests/ui/regression.spec.js:88-102` 只验证首页切深色 → 刷新 → 进 hcqr 页）。**建议**：在 `index.html:26-38` 与 6 个 paper 页的内联脚本上方各加一行契约说明（键名、取值集合、需同步的 8 处），并把 `tests/ui/regression.spec.js:100-101` 改成对 6 个 paper 页循环断言。
- **low** `scripts/ops/local-ci.sh:36` 与 `scripts/ops/macmini-bootstrap.sh:33` 的 `--help` 用硬编码行号区间截注释：前者输出以残句结尾（`:20` 是半句话），后者会把 `set -uo pipefail` 当说明打印出来。**建议**：改用 `cat <<'EOF'` 帮助块，或锚点匹配（如 `sed -n '/^# 用法:/,/^# 退出码/p'`）。
- **low** `README.md:19-27` 的 `data/` 清单只列 6 个文件，实际被跟踪 9 个（漏 `metadata-cache.generated.json` 与 `site-updated.generated.json`，两者都有真实依赖：`scripts/main.js:1425` fetch、`scripts/enrich-metadata.js:8` 写、`docs/QA_CHECKLIST.md:16` 验收）。**建议**：补两行并说明它们的生成命令。
- **low**（与 2.5 同源）`notes/README.md:29-36` 把作者本机的 Quarto 绝对路径（`E:\Dev\Apps\Quarto\bin\tools`）写进渲染步骤，全文仅 PowerShell 语法；`:40-43` 用 `python -m http.server` 而 `docs/MACMINI.md:151` 与 `run-lighthouse-check.js` 用 `python3`。新部署目标机是 macOS，照抄会失败。**建议**：改为通用前置条件并注明平台差异（如 `brew install pandoc`，Windows 读者括号里注明 `python`）。

### 2.4 逻辑隐患

- **medium** ★ `scripts/serve.js:25-30` 的路径校验用 `startsWith(ROOT)` 字符串前缀而非目录包含判定，可读到与仓库同前缀的兄弟目录。只读探针实测：`path.join(ROOT, "/../homepage-secret/x.txt")` 归一化后为 `D:\OneDrive\RUC\homepage-secret\x.txt`，`startsWith(ROOT)` 仍为 true。本机当前没有 `homepage*` 兄弟目录，且它只 bind `127.0.0.1`（`:39`），所以现在不可直接利用；但按 `docs/MACMINI.md:188` 用作局域网预览时读取面会扩大。**建议**：改成 `const rel = path.relative(ROOT, filePath); if (rel.startsWith("..") || path.isAbsolute(rel)) → 404`，并给 `:36` 的 `fs.createReadStream` 加 `error` 处理。
- **medium** ★ `scripts/enrich-metadata.js:284-293` 的 `--apply` 会把 arXiv 兜底链接写进未发表条目（没有检查 `published` 也没有检查 `hidden`），产生 `scripts/validate-site.js:147-156` 必然 FAIL 的 master；而 `scripts/build-site-data.js:164-170` 在派生层又把未发表条目的 `links.pdf/html` 置 null，造成"门禁报错但页面正常"的矛盾状态。**建议**：在 `applyCacheToMaster` 内复用 `scripts/validate-site.js:37-39` 的 `isPublishedPublication` 判据，未发表条目只允许写 `next.links.doi`；并把该判据抽到共享模块。
- **medium** ★ `scripts/check-contrast.js:37-136` 校验的是脚本内硬编码的 14 组颜色快照，全文件没有任何 IO（连 `require` 都没有），因此改 CSS 调色板后 `npm run check:contrast` 依旧输出 "OK: All configured color pairs satisfy WCAG AA."。它被 `scripts/ops/local-ci.sh:175` 与 `.github/workflows/site-checks.yml:69` 当门禁使用。**建议**：改为从 `enhanced-main.css` / `papers/shared/paper-theme.css` / `notes/style.css` 解析 CSS 变量取值，解析不到直接 FAIL 并打印变量名。
- **medium** `scripts/acceptance-check.js:129-133` 把"论文页数量 = 6"写死（报错文本 "Expected 6, got 7"），`:275-286` 还有 svcqr 专用 1 MB 阈值守卫（通用循环 `:226-245` 已按 100 KB 检查过它）。正常新增第 7 个论文页会让验收 FAIL 且失败原因与真实问题无关。**建议**：删掉计数断言，改为"papers 非空 + 与派生产物条数一致 + id 集合等于 master 中带 `paper_page` 的 id 集合"；把 svcqr 特例换成通用体积规则（或给 `data/paper-pages.json` 加 `min_pdf_bytes` 字段并在现有循环里断言），并把魔数提为具名常量。
- **medium** `index.html:219` 的 `<form class="pub-search" id="pub-search-form" role="search">` 没有 action/method、没有 submit 按钮、输入框（`:221`）与 4 个 filter select（`:222-225`）都没有 `name`，而 `scripts/main.js` 里 grep `submit` 0 命中、`pub-search-form` 全仓只有 `index.html:219` 一处。按 HTML 隐式提交规则，在筛选结果里按回车会 GET 刷新整页。**建议**：在 `initPublicationSearch` 里加 `form.addEventListener("submit", e => { e.preventDefault(); applyFilters(); })`，或把 `<form>` 降级为 `<div role="search">`。
- **medium** URL 里的非法/过期筛选值不回写 state：`scripts/main.js:781-894` 的 `renderPublicationFilterOptions` 在取值不在选项集合时只把下拉框归位到 "all"（`:805`/`:831`/`:863-865`/`:891-893`），却没改 `state.filters.*`，而 `getFilteredPublications`（`:743-768`）仍按 state 过滤。结果：4 个下拉框都显示"全部"但列表为空。**建议**：在归位分支同步写回 state，或末尾调一次 `applyFilters()` 让 UI 反向归一 state。
- **medium** 生成物回写 workflow 缺 rebase/重试：`.github/workflows/auto-sync-generated.yml:40-50` 在 checkout 后直接 `git add -A → commit → push`，没有 `pull --rebase`、没有重试，而姊妹 workflow `build-bookdown-notes.yml:48-53` 却有；`concurrency: main-writers` 只串行两个机器人，挡不住人工推送（`docs/MACMINI.md:21-22` 自己承认）。用 GITHUB_TOKEN 完成的 push 也不再触发任何 workflow，所以失败后既不会重跑也没有告警。**建议**：补 `git pull --rebase` 或重试循环，并给该 job 加 `if: failure()` 上报；长期按 `docs/MACMINI.md:236-240` 把回写迁到 mini。
- **medium** 站点域名只有一半是真源：`sitemap.xml` 与 paper 页 canonical 由 `data/site-master.json` 的 `base_url` 自动生成（`scripts/build-site-data.js:269`/`:313`/`:429`、`sync-paper-seo.js:23-44`，CI 有 `--check`），但 `robots.txt:4`、`index.html:9`/`:14`/`:15`/`:19`/`:43`、`scripts/main.js:908` 是硬编码，且 `scripts/validate-site.js` 与 `acceptance-check.js` 里 grep `base_url|robots|canonical|sitemap` 0 命中；`buildIndexHtml`（`scripts/build-site-data.js:41-51`）只替换 `?v=` 哈希。换域名会"半迁移"且 CI 全绿。**建议**：把 `robots.txt` 纳入 `OUTPUT_FILES` 由 baseUrl 渲染；`buildIndexHtml` 顺带重写 canonical/OG；`scripts/main.js:908` 改读 `link[rel="canonical"]` 或注入的 `window.__SITE_BASE_URL__`；在 `validate-site.js` 末尾加域名一致性断言。
- **medium** `index.html:325` 的页脚日期静态回退是"2026年8月10日"，而 `data/site-updated.generated.json` 是 `2026-09-17`（旧 38 天）；`scripts/main.js:1423-1443` 只在 fetch 成功后覆盖，失败时静默保留静态文本，`scripts/build-site-data.js:41-51` 从不碰这个日期，尽管 `README.md:12` 声称 "Single-source data workflow"。**建议**：在 `buildIndexHtml` 里同步改写回退日期（或注入占位符后替换），或让 `acceptance-check.js` 断言 `index.html` 的回退日期等于 `site-updated.generated.json` 的 `updated`。
- **medium** `CHANGELOG.md:10` 声称 CSS/JS 用内容哈希版本号，但 6 个 paper 页的 `paper-reader.js?v=2026031006` / `paper-theme.css?v=2026031006` 是冻结字面量（`papers/2025/hcqr/hcqr.html:687`、`papers/2025/svcqr/svcqr.html:706`、`papers/2025/poisson-rr/poisson-rr.html:682`、`papers/2022/gtwr-housing/gtwr.html:685`、`papers/2022/bgtwr-housing/bgtwr.html:679`、`papers/2021/mgtwr-variable-selection/mgtwr.html:676`），`scripts/acceptance-check.js:178-183` 只断言"存在 `?v=数字`"。**建议**：把 `hashText` 回写范围扩展到 6 个 paper 页，并把断言收紧为"等于当前内容哈希"。
- **medium** `data/site-master.json` 线上可读，因此 `hidden:true` 的条目（`qapsm-icu-bp`，ICU 血压轨迹手稿）只是不渲染、不是不公开；`.nojekyll` 关闭 Jekyll 后，下划线/点号目录也不构成保护。全仓文档没有一处说明这个语义。**建议**二选一并写进文档：接受公开（在 README 与 `docs/QA_CHECKLIST.md` 明确"`site-master.json` 线上可读，`hidden` 仅控制渲染"），或把站点文件移进 `site/` 并把真源移出发布目录（同时改 `scripts/build-site-data.js:8-20` 的路径常量）。（与 1.9 同源。）
- **low** `notes/_book/` 整个子站只靠仓库根 1 字节的 `.nojekyll` 存活（`index.html:80` 指向它；Jekyll 默认剔除下划线目录），而 `.github/workflows/site-checks.yml` 里 grep `jekyll|nojekyll` 0 命中，link-check 只扫 `index.html papers`（`:97`）。一旦 `.nojekyll` 被误删，笔记整站 404 而 CI 全绿。**建议**：在 `site-checks.yml` 的 syntax-check 加 `test -f .nojekyll || exit 1`；或把输出目录改成不带下划线的名字（`notes/book/`）从根上摆脱依赖。
- **low** `scripts/ops/` 三个脚本的选项取值不一致：`restore-homepage.sh:20-23` 与 `backup-homepage.sh:19-23` 用裸 `$2`（在 `set -euo pipefail` 下缺值直接以 "unbound variable" 中止，不走 usage）；`macmini-bootstrap.sh:29-31` 用 `"${2:-}"` 却仍 `shift 2`（该文件只有 `set -uo pipefail`，无 `-e`），空 `PORT` 会被渲染进 `scripts/ops/macmini/Caddyfile.tmpl:22` 的 `http://:__PORT__`，到启动才失败。另 `backup-homepage.sh:64-65` 用 `shasum`（macOS/Perl 系命令，Linux 为 `sha256sum`），而 `README.md:76-84` 把它当通用入口，且本仓库主工作目录是 Windows。**建议**：统一 `require_value()` 辅助函数（缺值打印 usage 并 exit 2）、给 PORT 加数字校验、用 `command -v` 预检 rsync/tar、`shasum -a 256 ... || sha256sum ...` 兼容写法，并在 README 注明"需要 rsync/tar/shasum，面向 macOS/Linux"。

### 2.5 性能与体积

- **medium** ★ `papers/2025/plgwqr/acta-math-app-cover-2026.webp`（398,934 B）只比同目录 jpg（447,036 B）小 11%，而同类封面的 webp 压缩率是 57–87%（svcqr 83%、mallows 87%、hcqr 75%）；它按 `enhanced-main.css:129-135` 渲染成 176–206 px 缩略图，800 px 宽的源是约 4 倍线性过采样。单张卡片约占首页封面图载荷的 56%，是最可能的 LCP 元素。**建议**：`cwebp -q 80 -resize 412 584 papers/2025/plgwqr/acta-math-app-cover-2026.webp -o tmp.webp` 后替换（预期 25–40 KB），并把 jpg 回退同样降采样。同类小问题：`salcdi-scarce-outcomes-cover` 的 webp（4,228 B）只比 jpg（4,324 B）小 2%，直接删 webp 让渲染器回退（`scripts/main.js:1133-1141` 已处理 `webp: null`）。
- **medium** `notes/_book` 45 个跟踪文件 1,490,224 B，占全部 185 个跟踪文件 27.20 MB 的 5.2%，是手写源码（`notes/*.Rmd|bib|css|yml|md` 13 个文件 87,198 B）的约 17 倍；其中 `notes/_book/libs` 20 文件 536,445 B 是冻结的第三方库（jQuery 3.6.0 / FontAwesome 4.7.0 / gitbook 2.6.7），不在 `.github/dependabot.yml` 覆盖内（只声明 npm 与 github-actions），`.gitattributes` 也没有 `linguist-vendored`/`linguist-generated` 标记，所以每次渲染提交都产生横跨 45 个生成文件的不可读 diff。**建议**：首选把产物移出 git（`.gitignore` 加 `notes/_book/`，workflow 改为 `actions/upload-pages-artifact` + `deploy-pages`）——这牵连发布链路与 `.nojekyll` semantic，属于"先不动"档；若必须继续提交，至少加 `.gitattributes` 的 linguist 标记折叠 diff。

### 2.6 仓库卫生

- **medium** ★ `.gitignore:14` 的 `*MacBook*` 无路径限定，且系统大小写不敏感（实测 `git config --get core.ignorecase` → `true`）——`git check-ignore -v --no-index docs/macbook-setup.md`、`notes/MacBook-notes.Rmd`、`cv/MACBOOK.pdf` 全部命中，即在这个刚新增 Mac mini 文档的仓库里，一份 `docs/macbook-*.md` 会被静默排除，`git status` 与 CI 都不会提示。4 个 OneDrive 冲突副本（`data/site-master-HouJian的MacBook Pro.json` 40410 B 等，全部 2026-08-11/13 的旧版）当前**确实不污染构建**：所有脚本对 `data/` 都是显式路径（`scripts/build-site-data.js:8-20`、`validate-site.js:7-13`、`acceptance-check.js:8-10`、`enrich-metadata.js:7-8`、`generate-paper-toc.js:7-8`、`sync-paper-seo.js:7`），唯一 `fs.readdirSync` 在 `scripts/validate-site.js:303` 且只遍历 `papers/`；但**零门禁**检测 `data/` 多出文件。**建议**：① 删掉磁盘上这 4 个副本（未被 git 跟踪，删除不影响仓库与构建）；② 把规则收窄为 `data/*MacBook*`；③ 给 `scripts/ops/macmini/Caddyfile.tmpl:33` 的 `@internal` 正则追加冲突副本模式 → 404；④ 给 `scripts/ops/backup-homepage.sh:52-56` 的 rsync 补 `--exclude "*MacBook*"`；⑤ 在 `scripts/validate-site.js` 加 `data/` 目录白名单断言。
- **medium** `notes/README.md:29-36` 的本机路径与平台语法问题（详见 2.3 末条）。
- **low** `sitemap.xml` 只有 7 个 `<loc>`（首页 + 6 个 paper 页），不含 `notes/_book/` 的 10 个 HTML，而 `index.html:80` 的"笔记"入口让它们站内可达。这不一定是缺陷（可能有意不收录），但意图没有记录。**建议**：在 `docs/QA_CHECKLIST.md` 写一句结论。要收录就在 `scripts/build-site-data.js:434` 的 `urlEntries` 加一条 `{ loc: baseUrl + "notes/_book/" }`（只加书入口页，别把 8 个章节页全塞进去）后 `--write`；不收录就在 `buildSitemap`（`:428`）上方加注释说明"有意排除"。
- **low** 以下是**已核实为"不是问题"**的项，列出来是为了防止后人重复排查：`hj.jpg`/`hj.webp` 不是冗余副本（`index.html:106-107` 是 webp + 非 webp 回退，`og:image` 用 webp）；`.nojekyll` 是 1 字节换行、符合用途；`.DS_Store` 未被跟踪且磁盘上不存在；被跟踪文件里无 0 字节空文件；`scripts/serve.js` 不是孤儿（`playwright.config.js:21` 使用）；`.gitignore:5` 的 `*~product.css` 当前匹配不到任何文件（失效但无害）；`sitemap.xml` 与 `papers/` 的 HTML 集合完全一致（`papers/2026/*` 等目录只有图片、无 HTML）。

### 2.7 隐私与暴露面

（1.1 / 1.8 / 1.9 / 1.12 已在第 1 节，下面是 medium 项）

- **medium** ★ CI 令牌权限过宽 + 输入注入 + 全历史 bundle：`.github/workflows/auto-sync-generated.yml:9-10` 是 `contents: write`，且同 job 先 `npm ci`（会执行依赖的 install/postinstall 生命周期脚本）；`.github/workflows/release-automation.yml:12-13` 是 `contents: write`，并把 `${{ github.event.inputs.tag }}` 直接拼进 `run:` 命令行（`${{ }}` 在 shell 解析前做文本替换，输入可含 `$(...)` 并被求值），同时把 `scripts/release.sh:77` 生成的 `release-artifacts/<tag>/rollback-main.bundle`（main 全量历史）作为公开 release 附件长期固化。**建议**：`site-checks.yml` 顶部加 `permissions: contents: read`；release 的输入改走 `env:`（脚本内用 `"$TAG"`/`"$MSG"`）；停止上传 rollback bundle，只留 CHANGELOG 与 rollback-point；`auto-sync-generated.yml:44` 的 `git add -A` 换成显式路径；htmlhint 固定版本。
- **medium** 备份脚本未排除 `.dsh/`：`scripts/ops/backup-homepage.sh:52-56` 的 rsync 只排除 `node_modules/`、`playwright-report/`、`test-results/`，随后 `:64` 把整个 `$SRC/` 打成 `homepage.snapshot.tar.gz`，因此 `.git/`（全量历史）与 `.dsh/`（agent 会话与用户粘贴附件，实测 `.dsh/tmp/` 有 142,464 / 98,640 / 21,159 B 的附件）都会进快照；而 `.gitignore:26-27` 正是因为它敏感才忽略。**建议**：rsync 补 `--exclude ".dsh/"`；需要保留历史时改用 `git bundle create ... --all` 单独存放，而不是整目录复制 `.git/`；并在 `docs/MACMINI.md` 的备份/恢复章节写明"备份包含仓库全量历史，不得外发"。
- **medium** 第三方统计脚本无 SRI、无隐私告知：`index.html:43` 的 Plausible（`data-domain="stork343.github.io"`，会把该账号名下所有 GitHub Pages 项目并入同一统计 property）与 `index.html:44` 的 busuanzi 均无 `integrity`/`crossorigin`（全文件 grep 只有 `:24` Google Fonts 预连接用了 `crossorigin`）；全站 grep `privacy|隐私|cookie|同意` 为空，页脚只有一条 `busuanzi_value_site_pv` 访问量（`:328-330`），没有任何收集说明或第三方清单。**建议**：给两个脚本固定具体版本并补 `integrity` + `crossorigin`（或自托管 busuanzi 副本）；在页脚加一行隐私说明写明两者会收到访问者 IP 与 Referer 并链到各自政策；若不接受该取舍，直接删 `index.html:44` 的 busuanzi 与 `:328-330` 的占位。

### 2.8 CI 与测试

- **medium** ★ CI 里无障碍测试整跑两遍：`.github/workflows/site-checks.yml:101-119` 的 `ui-regression` 执行 `npm run test:ui`，而 `playwright.config.js:6` 的 `testDir: './tests/ui'` 会让它跑全部三个 spec（`visual.spec.js:7-10` 在非 darwin 直接 skip，故 ubuntu 上实跑 `regression` + `accessibility`）；`:121-139` 的 `a11y-check` 又把 `accessibility.spec.js` 跑一遍，两个 job 各自重复 `npm ci` + `npx playwright install --with-deps chromium`。`docs/MACMINI.md:168-174` 已记录该浪费并给出修法（改用 `test:ui:core`），`scripts/ops/local-ci.sh:190-195` 已经这么做。**建议**：`site-checks.yml:119` 改为 `npm run test:ui:core`（或直接删 `a11y-check` job）；顺手修正 `docs/MACMINI.md:172` 对 macOS 行为的错误描述（visual-regression job 实际只跑 `npm run test:visual`）。同源重复还出现在 `scripts/release.sh:84-86` 与 `README.md:56-58`、`docs/QA_CHECKLIST.md:10-12`、`docs/RELEASE_ROLLBACK.md:21-23`，建议一并收敛。
- **medium** `site-checks.yml` 是唯一未声明 `permissions` 的 workflow（全文 188 行无该块），却在 `:98-99` 把 `secrets.GITHUB_TOKEN` 交给第三方 action `lycheeverse/lychee-action@v2`（`:81`，未固定到 commit SHA）。仓库实际默认权限无法从外部确认（匿名 API 返回 401），所以"6 个只读 job 全部持有可写 token"是条件结论。**建议**：补 `permissions: contents: read`；把仓库 Settings → Actions → General → Workflow permissions 固化为 "Read repository contents"；把 lychee 固定到具体版本/SHA。
- **medium** 4 个 workflow、11 个 job 全部没有 `timeout-minutes`（默认 360 分钟/job），也没有任何失败上报（grep `if: failure` 只命中 `.github/workflows/site-checks.yml:162` 的产物上传）。**建议**：按 job 加合理超时（syntax 10、link 20、ui/a11y 15、visual 20、lighthouse 15、auto-sync 20、bookdown 30、release 60 分钟），并在 workflow 末尾加失败通知（issue/webhook），给 main 开启 required status check——否则超时与通知都只是止损。
- **medium** CI 用 `npx --yes htmlhint` 现场拉取未固定版本（`.github/workflows/site-checks.yml:33`/`:36`，`scripts/ops/local-ci.sh:170` 同），而其余工具链（`@playwright/test 1.62.1`、`@axe-core/playwright 4.13.0`、`lighthouse 13.4.1`）都锁在 `package.json` 并有 `package-lock.json`。一次上游大版本变更就能在没改仓库任何一行时让 `syntax-check` 变红（或漏检）。**建议**：把 htmlhint 纳入 devDependencies 锁版本，改用 `npx htmlhint`，并在 `.github/dependabot.yml` 的 test-tooling 分组补上它。
- **medium** 渲染工具链三处不锁版本：`.github/workflows/build-bookdown-notes.yml:30` 的 `setup-r@v2`（无 `r-version`）、`:33` 的 `setup-pandoc@v2`（无 `pandoc-version`）、`:38` 的 `packages: bookdown`（取 CRAN 最新）；`notes/README.md:29-35` 又指导本地用 Quarto 自带 pandoc + 本机 R 渲染，两条路径写同一批被跟踪文件（workflow `:48` 的 `git add notes/_book` 与本地 `notes/_book` 完全重叠），`notes/README.md:59-62` 自己记录了 pandoc 3.x 移除 `fancy_latex`、bookdown 0.47 的 lua 行为变化会导致定理环境被丢弃。**建议**：三处都锁死（具体版本先在 CI 里打印一次 `sessionInfo()` / `pandoc --version` 回填），并明确"本地渲染结果不要提交，`_book` 只由 CI 写"。**说明**：churn 的实际频次无法在只读审计中复现（不能本地跑渲染），此条是基于"版本不锁 + 双路径写同一文件"的推理。
- **medium** 视觉回归只认 darwin 基线且对非 darwin 静默 skip：`tests/ui/visual.spec.js:7-10` 的 `test.skip(process.platform !== "darwin", ...)`，4 个快照全是 `-darwin` 后缀（`tests/ui/visual.spec.js-snapshots/homepage-{navbar,main,paper-topbar,paper-sidebar}-chromium-darwin.png`）。在 Windows 上 `npm run test:visual` 是 "0 passed / 2 skipped"，而 `README.md:58`、`scripts/release.sh:86`、`docs/QA_CHECKLIST.md:12` 把它当发布前必跑门禁，形成"跑过了其实是空的"假安全感。**建议**二选一并写进文档：收敛到单一权威环境（推荐 CI 用 linux 容器 + `--update-snapshots` 生成 `-linux` 基线，删现有 darwin png 与 macos-latest job），或按 `docs/MACMINI.md:164-166` 删掉 CI 视觉 job 并明确"视觉仅本机 darwin 手动跑"；同时把进程级 `test.skip` 换成 reporter 里显式可见的跳过。
- **medium** 无障碍门禁覆盖面小于文档承诺：`tests/ui/accessibility.spec.js:21-25` 的首页 axe 用 `includeSelector='main'`（经 `:6-8` 的 `builder.include`）把 navbar、footer 与 `#theme-toggle` 排除在外，且只测中文浅色态（`README.md:7` 承诺中英切换与深色持久化）；另一个 test（`:27-31`）只打 `papers/2025/hcqr/hcqr.html`，另外 5 个论文页、英文态、深色态全无 axe 覆盖。可被漏掉的具体缺陷：`index.html:222-225` 的 4 个筛选下拉框只写死英文 `aria-label`（`Year filter` 等）、未带 `data-i18n-aria-label`，而 `scripts/main.js:400-403` 只遍历带该属性的节点，所以切到中文后标签仍是英文（对照 `index.html:221` 的搜索框有该属性，说明是遗漏）。**建议**：首页去掉 `main` 限定（传 `undefined` 扫全文档），增加英文态与深色态各一轮，用 `data/paper-pages.json` 的路径参数化 6 个页面；同时给 4 个 select 补 `data-i18n-aria-label`。
- **medium** 渲染 workflow 会被自己的提交再次触发：`.github/workflows/build-bookdown-notes.yml:7-8` 的 `paths: notes/**` 与 `:44-56` 把 `notes/_book` 提交回 main 重叠，且没有排除路径或 `if: github.actor != 'github-actions[bot]'` 守卫；同时 `notes/index.Rmd:5` 的 `date: "`r Sys.Date()`"` 会写进产物（`notes/_book/index.html:26`/`:311`），使产物无法按字节复现。同日第二轮会在 "No rendered changes" 处终止（只是白跑一轮），跨 0 点则会因日期变化再触发一轮。**建议**：把 `paths` 收窄到手写输入（如 `notes/*.Rmd`、`notes/*.yml`、`notes/book.bib`、`notes/style.css`），或给 render job 加 bot 守卫；把 `Sys.Date()` 换成固定日期或最近一次源码提交时间。
- **low** 测试超时层层放宽，性能退化可在绿测中隐藏：`playwright.config.js:7` 的 `timeout: 180000` 与 `:8-10` 的 `expect.timeout: 30000`，各用例内部又有更大值（`tests/ui/regression.spec.js:5` 45s、`:20` 90s、`:27/:31` 90s/30s、`:57` 45s；`tests/ui/accessibility.spec.js:23` 45s、`:29-30` 45s；`tests/ui/visual.spec.js:15` 45s、`:27-28` 60s），而 `tests/` 里 grep `performance|timing|budget|duration` 0 命中。**建议**：给关键路径加显式预算断言（如首页出版物首卡可见 < 3 s、点击 TOC 到 `syncPageQuery` 生效 < 2 s），并把 90s 收敛到测试级 timeout 之下并写清理由，让"超时"真正意味着失败而不是慢。

**重复记账说明**：71 条 finding 中有若干跨切片重复——`data/paper-pages.json` 身份问题被 3 个切片分别记录（scripts high / data medium / 文档 medium）；`scripts/enrich-metadata.js` 的写入问题被 2 个切片记录（scripts medium / data high）；CI 无障碍重复执行被 2 个切片记录（运维 medium / 测试 medium）；OneDrive 冲突副本与 `data/` 线上可读也各被 2–3 个切片记录。去重后独立问题数明显少于 71。

---

## 3. 建议的清理顺序

### A. 立刻做（低风险、影响明确、单文件可回滚）

| # | 动作 | 风险 | 回滚 |
|---|---|---|---|
| 1 | 修语言切换日期回退（`scripts/main.js` 的 `applyI18nText`/`setLanguage` 与 `loadSiteMeta` 协作） | 极低 | `git revert` 单个提交 |
| 2 | 修 `index.html:325` 的静态回退日期，并让 `scripts/acceptance-check.js` 断言它等于 `data/site-updated.generated.json` 的 `updated` | 极低 | 同上 |
| 3 | 修搜索框回车（`index.html:219` 加 submit 监听，或把 `<form>` 降级为 `<div role="search">`） | 极低 | 同上 |
| 4 | 让 `scripts/main.js:781-894` 在归位下拉框时同步写回 `state.filters.*` | 低（会改变非法筛选值的行为，属修 bug） | 同上 |
| 5 | 处理 CV PDF：换掉 `cv/RUC_CV.pdf` 的内容；`git rm cv/hou-jian-cv-zh.pdf`。**不做**历史重写 | 低 | `git revert`；文件可由 git 历史恢复 |
| 6 | 改 `scripts/ops/backup-homepage.sh:71-72` 的打印命令为 `restore-homepage.sh`，给 rsync 补 `--exclude ".dsh/" --exclude "*MacBook*"` | 低 | 同上 |
| 7 | 修 `README.md:23` 对 `paper-pages.json` 的描述（定论前也可先写 "generated, do not hand-edit"） | 极低 | 同上 |
| 8 | 决定 visual-regression job 的去留并执行（删 job，或改成与内容长度解耦的快照 + 重生基线） | 中（会改变视觉门禁覆盖） | 恢复 workflow 与快照文件 |

另外把"立刻做"里的两条低成本守卫一起加上：在 `.github/workflows/site-checks.yml` 的 syntax-check 里加 `test -f .nojekyll || exit 1`，以及给 main 开启 required status check。

### B. 下次改动时顺手做（不要为它们单独开 PR，改动本身要过门禁）

1. **删无用产物与孤儿**：`data/search-index.generated.json`、12 个零引用图片、`icon/google.png`、`papers/shared/reader.css`、`notes/_book` 里 6 张旧图 + `404.html`、`papers/2025/hcqr/data-line.*`。每删一批就跑 `node scripts/build-site-data.js --check && node scripts/validate-site.js && node scripts/acceptance-check.js`。风险：低（都是可再生或零引用文件）；回滚：`git revert`。**注意 `papers/2022/gtwr-housing/mgtwr.webp` 与 2021 版同名不同内容，删前用 dir-qualified grep 复核。**
2. **收敛重复实现**：`generate-paper-toc.js` 降级为纯校验器、抽 `scripts/lib/*`、删 `scripts/main.js:896-945` 的 JSON-LD 客户端现算、删 `createSeparator` 与 `.separator` 规则、删 `project-*` 与 `--space-*` 等死代码。**清理 CSS/JS 后必须跑一次 `node scripts/build-site-data.js --write` 刷新 `?v=` 内容哈希**，否则首页会引用旧文件。风险：中（改动面广）；回滚：`git revert` + 重跑 `--write`。
3. **CI 卫生**：给 job 加 `timeout-minutes`、`site-checks.yml` 加 `permissions: contents: read`、`ui-regression` 改用 `test:ui:core`、htmlhint 锁版本、`auto-sync-generated.yml:44` 的 `git add -A` 收窄为显式路径并补 `git pull --rebase`、加失败通知。风险：中（改 CI 会立刻影响后续每次 push 的红绿，建议一次只改一项）；回滚：恢复 workflow 文件。
4. **文档对齐**：`papers/README.md` 结构清单与重建配方、`CHANGELOG.md:12` 的 `docs/workflows/`、README 的 Repository Layout 缺项、`data/` 清单缺项、`homepage-theme` 契约注释、两个 `--help` 的行号魔法、`notes/README.md` 的本机路径。风险：极低；回滚：`git revert`。
5. **`.gitignore` 收窄 + `data/` 目录白名单断言 + 删磁盘上 4 个冲突副本**。风险：中（白名单断言会开始对任何新增的 `data/` 文件报错，这是预期行为，但需要一次适应）；回滚：改回 `.gitignore` 那一行并删掉断言。
6. **站点域名参数化 + `robots.txt` 纳入生成物**：等到真有换域名需求时一起做，否则只是增加 `--check` 的复杂度。

### C. 先不动（牵连面大，需要单独决策）

1. **`notes/_book/` 的入库方式与发布链路改造（移出 git / 改 Actions 部署）**：产物入库是刻意设计（`notes/README.md:25`），且当前整站靠 1 字节 `.nojekyll` 存活；改进要同时验证根 `index.html:80` 的入口、Jekyll 行为与 CI 回写。风险：中高（做错会让笔记整站 404，且 CI 不一定报错）；回滚：恢复 `notes/_book/` 与 `.nojekyll`、把 workflow 改回提交产物。**在此之前先做 A 档里的 `.nojekyll` 存在性断言。**
2. **Pages 从仓库根发布 → Actions 白名单产物目录**（1.9 的正确修法）：会动到 `notes/_book` 的发布方式与所有绝对路径。风险：中高；回滚：把 Pages Source 改回 "Deploy from a branch"。
3. **`beamer_presentation.tex` 迁出仓库 / 10 张 deck 图减体积**：迁到 `talks/` 零收益（仍会被发布），减体积要动不可再生的母版 PNG，而仓库里没有任何图像工具链（grep `sharp|cwebp|imagemagick|mogrify` 全空）。风险：中（改坏 LaTeX 引用）；建议等独立 talk 仓库时一并处理。
4. **`release-automation.yml` / `scripts/release.sh` 的存废**：这条链路从未运行过，删除是净收益，但删之前要先决定发布流程（手工 tag 还是修好它）。风险：低但决策依赖；回滚：恢复文件。
5. **`git filter-repo` + force push 清历史**：不可逆，且会与公开 release bundle、历史中的 PDF blob 纠缠。**本次不建议做**——先换掉当前 HEAD 上的文件即可，手机号按已泄露处理。
6. **4 份 CNKI PDF 的处置**（1.8）：等确认各期刊自存档政策后再动，避免误删有自存档许可的作者稿。

---

## 4. 明确不建议动的部分

保持现状是对的，避免过度清理：

- **`notes/_book/` 的已提交产物不要删。** 这是刻意入库并被 GitHub Pages 直接服务的（`notes/README.md:25` + 仓库根 `.nojekyll` + 无 `_config.yml`），产物与源码当前完全一致（`\@ref` 残留 0、字面 `??` 0、`notes/index.Rmd` 的 7 个章节引用全部解析、`git status notes/` 干净）。要改的是"怎么发布"，不是"删掉产物"。
- **10 张仅被 `beamer_presentation.tex` 引用的 `papers/` 图片不要删。** 它们是 LaTeX 构建的输入（`beamer_presentation.tex:8` 的 `\graphicspath`），删了 deck 构建就坏。要减体积先改 deck 的组织方式。
- **6 个 paper 页的 `<picture>` webp→jpg 回退与 width/height 不要动。** 16 个带图条目全部有尺寸属性、回退逻辑正确，不存在 CLS 或缺失元数据缺陷；`papers/README.md` 也明文规定 per-paper 目录存放 cover/figure images。`scripts/validate-site.js:298-315` 的"未引用资产"闸门被刻意限定为 PDF，不含图像，是有意划定的规则边界。
- **`hj.jpg` 与 `hj.webp` 都保留。** 两者都被引用（`index.html:106` 是 `<source srcset="hj.webp">`，`:107` 是 `<img src="hj.jpg">` 非 webp 回退），`og:image` 用 webp；jpg 只在浏览器不支持 webp 时取，没有额外流量代价。
- **`scripts/serve.js` 不是孤儿，不要删**（`playwright.config.js:21` 与 `docs/MACMINI.md:188` 都在用），只修它的路径校验（2.4）。
- **`.nojekyll`（1 字节换行）不要删。** 它符合用途，删了笔记整站 404。要加的是"存在性断言"，不是删除。
- **`papers/2025/svcqr/svcqr.pdf` 与 `papers/2025/hcqr/hcqr.pdf` 保留。** 它们分别是 arXiv GenPDF 与 pdfTeX 作者稿，是合规的；1.8 建议处置的只是 4 份 CNKI 出版社排版件。
- **`data/` 全部用显式路径读取的约定不要改。** 这是当前 OneDrive 冲突副本不污染构建的原因（唯一 `readdirSync` 在 `scripts/validate-site.js:303`，只遍历 `papers/`）。要加的是目录白名单断言，不是改成目录 glob。
- **`docs/MACMINI.md` 与 `scripts/ops/` 的新部署套件不要推翻重写。** 整体质量高（`set -uo pipefail`、门禁不中断、bash 3.2 兼容、Caddyfile 屏蔽 `.git`），只修选项取值与平台依赖声明。
- **`tests/ui/visual.spec.js-snapshots/` 的 darwin 基线暂时留着。** 在决定视觉门禁归属（CI 还是本机）之前，不要同时维护两套基线。
- **`data/paper-toc.generated.json` 的当前内容不要手改。** 在两个生成器收敛之前它是一致的（两条 `--check` 都 OK），手改只会引入新的漂移。
- **`cv/hou-jian-cv-zh.tex` 删 PDF 前别顺手一起删。** 它不是那两份中文 PDF 的源（无手机号、只渲染 1 页），但在仓库里可能还有别的用途，先确认。
- **`data/metadata-cache.generated.json` 不要直接删了了事。** 它是被 `scripts/build-site-data.js:64-71` 读取的声明式生成物，先按 2.2 的 (a)/(b) 二选一，再决定删不删。

---

## 5. 覆盖范围与未核实项

### 5.1 已审切片（10 个，全部只读）

1. `scripts/` 下全部 JavaScript 工具链（10 个脚本，交叉核对 `package.json`、CI workflow、`local-ci.sh`、`playwright.config.js`、README/docs、样式表、`data/` 与 git 跟踪状态）
2. 运维脚本与 CI 工作流（`scripts/release.sh`、`scripts/ops/*`、`scripts/ops/macmini/*`、`.github/workflows/` 下 4 个实际存在的 workflow、`.github/dependabot.yml`）
3. 首页前端三件套（`index.html` 342 行、`enhanced-main.css` 305 行、`scripts/main.js` 1616 行）
4. `data/` 数据层（真源与全部派生）
5. `papers/` 页面与静态资源（67 个跟踪文件 / 21.10 MiB）
6. `notes/` bookdown 产物（58 个跟踪文件 + `build-bookdown-notes.yml` + `.gitignore` 规则）
7. 测试与测试配置（`tests/ui/*.spec.js`、`tests/` 其余文件、`playwright.config.js`）
8. 文档、注释与指代清晰度
9. 仓库整体卫生与孤儿文件
10. 隐私、合规与暴露面

审计方式：只读。未修改 / 创建 / 删除任何文件（本报告除外），未执行任何 git 写操作，只跑了 `--check` 类门禁与只读探针。

### 5.2 统计

71 条 finding：**1 critical / 11 high / 49 medium / 10 low**，含跨切片重复（见第 2 节末）。按切片：`scripts/` 8 条（1 high、7 medium）、运维与 CI 8 条（1 high、6 medium、1 low）、首页前端 8 条（2 high、4 medium、2 low）、`data/` 7 条（1 high、5 medium、1 low）、`papers/` 8 条（1 high、6 medium、1 low）、`notes/` 5 条（4 medium、1 low）、测试 5 条（1 high、3 medium、1 low）、文档 8 条（1 high、6 medium、1 low）、仓库卫生 6 条（4 medium、2 low）、隐私与暴露面 8 条（1 critical、3 high、4 medium）。

### 5.3 对抗性验证覆盖情况（重要）

只覆盖了 12 条 critical/high 中的 10 条：

- **2 条被证伪（verdict `refuted`）→ 按 low 处理，不要按原报告执行**：导航 hash 改写（1.11）、在审期刊名（1.12）。
- **1 条未验证（verdict `not_verified`）→ 待人工确认**：`data/paper-pages.json` 身份混淆（1.10）。
- **7 条 confirmed 但严重度下调**：1.1→medium、1.2→medium、1.3→medium、1.4→medium、1.5→medium、1.6→medium、1.7→low。
- **2 条 high 未进入对抗性验证 → 待人工确认**：4 份 CNKI PDF（1.8）、Pages 从仓库根发布（1.9）。这两条的证据本身是直接实测（`pdfinfo` / `pdftotext` / 线上 200），缺的是政策性与设置性的确认。

### 5.4 证据不完整 / 需要人工确认的点

- `release-automation.yml` 全历史 0 次运行，其**实际行为无法验证**（只能确认它存在且被文档指定为发布路径）。
- `notes` 渲染的 churn 频次**无法在只读审计中复现**（不能在本地跑 bookdown 渲染），相关结论是"版本不锁 + 双路径写同一文件"的推理，不是观测到的历史事故。
- 历史中是否存在手机号的明文形态**未穷尽核实**（`git log -S` 因仓库体积超时；PDF blob 在历史中保留是确定的）。
- 仓库 Settings → Actions 的默认 Workflow permissions **无法从外部确认**（匿名 API 返回 401），所以"6 个只读 job 持有可写 token"是条件结论。
- Pages 的 Source 设置**未直接核对**（由"根有 `.nojekyll` + 无部署 workflow"推断），建议在仓库 Settings → Pages 确认。
- 线上可达性用 `web_fetch` 的对照探测**间接确认**（沙箱内直连超时，未下载线上文件比对哈希）。
- 运维切片提到"5 个 workflow"，**实际存在 4 个**（`site-checks`、`auto-sync-generated`、`build-bookdown-notes`、`release-automation`）；提示中的"5 个"应为把 `dependabot.yml` 计入，或按已被删除的 `update-visitor-stats.yml` 计。以 4 个为准。
- `docs/MACMINI.md`、`scripts/ops/local-ci.sh`、`scripts/ops/macmini/*` 在审计时处于**未跟踪状态**（工作区文件），相关结论基于工作区内容；若这些文件最终未提交，本报告中针对它们的建议在提交后才有意义（其中"删除 CI 视觉 job"的建议尤其依赖这一点——删掉后仓库内将不再有任何受强制的视觉门禁）。
- 若干"当前不构成风险"的判断**依赖运行环境**：`data/` 冲突副本不污染构建这一结论依赖"所有脚本都用显式路径读取 `data/`"的不变量，新增任何目录遍历脚本（或改用 glob）都会立刻改变结论。
- 严重的**跨切片计数重复**已在本报告去重说明中列出；若上游需要精确的独立问题数，需按"同一根因"再合并一次。